<template>
  <div class="vp-raw flex flex-wrap gap-2">
    <DdtwButton
      color="default"
      pill
    >
      Default
    </DdtwButton>
    <DdtwButton
      color="alternative"
      pill
    >
      Alternative
    </DdtwButton>
    <DdtwButton
      color="dark"
      pill
    >
      Dark
    </DdtwButton>
    <DdtwButton
      color="light"
      pill
    >
      Light
    </DdtwButton>
    <DdtwButton
      color="green"
      pill
    >
      Green
    </DdtwButton>
    <DdtwButton
      color="red"
      pill
    >
      Red
    </DdtwButton>
    <DdtwButton
      color="yellow"
      pill
    >
      Yellow
    </DdtwButton>
    <DdtwButton
      color="purple"
      pill
    >
      Purple
    </DdtwButton>
  </div>
</template>

<script setup>
import { DdtwButton } from '../../../../src/index'
</script>
